#!/usr/bin/env bash
# manage_my_process script - This will be the daemon process
while true
do
    echo "I am alive!" >> /tmp/my_process
    sleep 2
done

#!/bin/bash
# 101-manage_my_process script - This will manage the daemon process
case "$1" in
    start)
        # Start the manage_my_process script
        ./manage_my_process &
        # Save the PID to the pid file
        echo $! > /var/run/my_process.pid
        echo "manage_my_process started"
        ;;
    stop)
        # Read the PID and kill the process
        kill "$(cat /var/run/my_process.pid)"
        # Remove the PID file
        rm -f /var/run/my_process.pid
        echo "manage_my_process stopped"
        ;;
    restart)
        # Stop the process
        kill "$(cat /var/run/my_process.pid)"
        rm -f /var/run/my_process.pid
        # Start the process again
        ./manage_my_process &
        echo $! > /var/run/my_process.pid
        echo "manage_my_process restarted"
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        ;;
esac
