#!/usr/bin/env bash
#This script will
PID_FILE="/var/run/my_process.pid"
PROCESS_SCRIPT="./manage_my_process"

start() {
    if [ -f "$PID_FILE" ]; then
        echo "Process is already running."
        exit 1
    fi
    $PROCESS_SCRIPT &
    echo $! > "$PID_FILE"
    echo "manage_my_process started"
}

stop() {
    if [ ! -f "$PID_FILE" ]; then
        echo "Process is not running."
        exit 1
    fi
    kill "$(cat $PID_FILE)"
    rm -f "$PID_FILE"
    echo "manage_my_process stopped"
}

restart() {
    stop
    start
    echo "manage_my_process restarted"
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        exit 1
        ;;
esac
