#!/usr/bin/env bash
#This script will displays the PID, along with the process name, of processes whose name contain the word bash.
i=0
while [ $i -le 1 ]; do
     echo "To infinity and beyond"
     sleep 2
done
