#!/usr/bin/env bash
#This script terminates 4-to_infinity_and_beyond
# Get the PID of the process
pid=$(pgrep -f "bash ./4-to_infinity_and_beyond")

# Check if the PID exists
if [ -n "$pid" ]; then
# Send the SIGTERM signal to the process
kill "$pid"
fi
