#!/usr/bin/env bash
# This script is displaying "Best School" 10 times but in the 9th iteration it prints hi

i=1
while [ $i -le 10 ]; do
    echo "Best School"
    ((i = i + 1))
    if [ $i == 9 ]; then
    echo "Hi"
    ((i = i + 1))
    fi
done

