#!/usr/bin/env bash
#This script implements the conditional statements inside a loop
i=1
while [ $i -le 10 ]; do
    if [ $i == 4 ]; then
        echo "bad Luck"
        ((i++))
    elif [ $i == 8 ]; then
        echo "good luck"
        ((i++))
    else
        echo "Best School"
        ((i++))
    fi
done
